version: '3.7'
services:
  dashboard:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_HOST: mongodb
    volumes:
      - type: bind
        source: ../dashboard-data/config_files
        target: /opt/code/config_files

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - type: bind
        source: ../dashboard-data/mongodata
        target: /data/db

volumes:
  mongodata:
  config_files:
