dashboard:
  image:
    repository: sprints-dashboard
    tag: local
  ingress:
    enabled: True

jira:
  config:
    jira:
      base_url: https://limejump.atlassian.net/rest/agile
    teams:
      - name: cx
        board_id: 130
      - name: dar
        board_id: 145
      - name: voyager
        board_id: 140
      - name: infra
        board_id: 142
      - name: embedded
        board_id: 126
      - name: helios
        board_id: 163
  credentials:
    existingSecret: jira-credentials

dataCollection:
  enabled: true
  image:
    repository: sprints-dashboard
    tag: local

mongodb:
  auth:
    existingSecret: mongo