apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: sprints
  name: sprints-etl
spec:
  schedule: "01 16 * * FRI"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: latest-sprints
            image: sprints-dashboard:local
            command: ["python"]
            args: ["cli.py", "extract", "sprints", "latest"]
            env:
              - name: DB_HOST
                value: mongo-mongodb
              - name: DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: mongo-mongodb
                    key: mongodb-root-password
              - name: TOKEN
                valueFrom:
                  secretKeyRef:
                    name: limejump-jira
                    key: access-token
          restartPolicy: Never
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: sprints
  name: historic-issues-etl
spec:
  schedule: "15 16 * * FRI"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: latest-sprints
            image: sprints-dashboard:local
            command: ["python"]
            args: ["cli.py", "extract", "issues"]
            env:
              - name: DB_HOST
                value: mongo-mongodb
              - name: DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: mongo-mongodb
                    key: mongodb-root-password
              - name: TOKEN
                valueFrom:
                  secretKeyRef:
                    name: limejump-jira
                    key: access-token
          restartPolicy: Never