architecture: standalone
useStatefulSet: true
initContainers:
  - name: migrations
    image: migrations:local
    env:
      - name: DB_HOST
        value: mongo-mongodb
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mongo-mongodb
            key: mongodb-root-password
